hw_1: Git tag plugin
TratsyakEvgen/ClevertecBackendCourse pull request #1
Opened 2024-08-13 13:12 UTC by TratsyakEvgen

2024-08-18 11:07 UTC, DimaLamaka requested changes
Круто, что исопльзовал интерфейсы, использовал мой пример  с мапой, ну или увидел где-то)
Раздели на несколько тасок, ну и поправь комменты, ну и вообще, так как у тебя интерфейсы маленький и они функциональные, ты мог задавать поведение прямо в мапе, через лямду, потому что у тебя реализация маленькая и в мапе тоже выглядело бы локонично

2024-08-18 11:07 UTC, DimaLamaka commented on src/main/java/ru/clevertec/course/task/GitTagTask.java
> +        throwIfLocalRepositoryNotExists();
нет проверки, установлен гит вообще или нет

2024-08-18 11:07 UTC, DimaLamaka commented on src/main/java/ru/clevertec/course/task/GitTagTask.java
> +        }
раздели эту таску на несколько зависимых друг от друга тасок, вдруг я хочу только проверки выполнить, смогу ли я вообще поставить тэг или нет, или допустим посмотреть последние удаленные тэги,
хотя бы несколько тасок:
- проверки(можно их тоже делить на несколько по желанию)
- получение тэгов и сохранение например их в extenstion свой
- создание нового тэга и пуш его

2024-08-18 11:07 UTC, DimaLamaka commented on src/main/java/ru/clevertec/course/task/commad/impl/CommandExecutorImpl.java
> +    public List<String> getResult(String... command) {
не забывай сделать проверку для таких сервисов, потому что тут большой шанс, если кто-то будет еще делать и дорабатывать, то не факт, что они не передадут null или пустой массив просто

2024-08-18 11:07 UTC, DimaLamaka commented on src/main/java/ru/clevertec/course/task/version/Version.java
> +public interface Version {
наименование, наименование интерфейсов должно означать какое-то действие, например Runnable (имеет возможность бежать(запускаться)) ну или используй абстрактный класс, он более подходит для того, где используется какое-то состояние

2024-08-18 11:07 UTC, DimaLamaka commented on src/main/java/ru/clevertec/course/task/version/impl/VersionFactoryImpl.java
> +                .split("\\.");
зачем мапить в дабл, а что если придет тэг 1.0.1, как себя поведет программа?
поведение будет не правильным, я предлогаю тебе сделать так:
- написать мапер, который будет каждую строку мапить в объект VersionImpl
- далее, ты можешь написать свой компаратор для объектов такого типа
- взять последний и возвращать его
Тебе не надо будет никаких лишних манипуляций со строками, парсингами и т.д.

2024-08-18 11:07 UTC, DimaLamaka commented on src/main/java/ru/clevertec/course/task/version/impl/VersionFactoryImpl.java
> +        return new VersionImpl(Integer.parseInt(stringVersionValue[0]), Integer.parseInt(stringVersionValue[1]));
если что сделаешь, выше то всё исправится и тебе не надо будет делать таких костылей

2024-08-18 11:07 UTC, DimaLamaka commented on src/main/java/ru/clevertec/course/task/version/impl/MasterVersionUpdater.java
> +        return version.toString();
а если мажорная версия повышается, не должны ли мы до нуля скинуть все остальные?)

2024-08-18 11:07 UTC, DimaLamaka commented on src/main/java/ru/clevertec/course/task/version/VersionUpdater.java
> +    String update(Version version);
у тебя интерфейс называется VersionUpdated, он судя по названию, должен только обновить version, почему на выходе тогда стринга?)

2024-08-18 11:07 UTC, DimaLamaka commented on src/main/java/ru/clevertec/course/task/version/impl/VersionUpdaterFactoryImpl.java
> +    private static final Map<String, Supplier<VersionUpdater>> SUPPLIER_MAP = new HashMap<>();
наименование какое-то слишком общее, попробуй хотя бы UPDATER_SUPPLIERS

2024-08-18 11:07 UTC, DimaLamaka commented on src/main/java/ru/clevertec/course/task/version/impl/VersionUpdaterFactoryImpl.java
> +        return versionUpdaterSupplier.get();
Можно и на цепочку Optional заменить, но не обязательно)

2024-08-19 06:08 UTC, TratsyakEvgen commented on src/main/java/ru/clevertec/course/task/version/impl/MasterVersionUpdater.java
> +        return version.toString();
> а если мажорная версия повышается, не должны ли мы до нуля скинуть все остальные?)

Минорная версия здесь обнуляется
//increaseMajorVersion() set minor=0 - добавлю комментарий

2024-08-19 11:58 UTC, DimaLamaka commented on src/main/java/ru/clevertec/course/task/version/impl/MasterVersionUpdater.java
> +        return version.toString();
твоя логика дублирования путает, либо перенеси всю логи поднимания версий в объект для версий, либо в апдейтеры с возвращением нового объекта с новыми полями уже

2024-08-20 07:31 UTC, DimaLamaka approved these changes

2024-08-20 07:31 UTC, DimaLamaka commented on src/main/java/ru/clevertec/course/task/commad/impl/CommandExecutorImpl.java
> +            throw new CommandExecutorException("Command must have value");
Проверки выше можно объеденить и просто написать, что command is not valid

2024-08-20 07:31 UTC, DimaLamaka commented on src/main/java/ru/clevertec/course/task/version/impl/updater/SnapshotVersionUpdater.java
> +        return new Version(major, minor, "-SNAPSHOT");
-SNAPSHOT и -rc можно вынести в константы

2024-08-20 07:58 UTC, merged